### ISSUE TITLE
Conflicts with fltk: installs files into the same place

### ISSUE THREAD

**Issue by yurivict** [original-male/ntk#10]
> pkg-static: ntk-g92365ec conflicts with fltk-1.3.4 (installs files into the same place).  Problematic file: /usr/local/lib/libfltk.so.1

You need to make names unique, so that people will not need to uninstall other things for ntk.

**Comment by original-male** [comment]
You need to provide more information in your bug reports.

Are you using a packaged version of NTK or building from the source?

**Comment by yurivict** [comment]
I am trying to create a FreeBSD port, and found this conflict.

**Comment by original-male** [comment]
You can read the wscript yourself and see that it references. No objects named *fltk*. Nor does such an object install on Linux. I have to assume that the problem lies in your packaging.

**Comment by yurivict** [comment]
Yes, you are right, I had some leftovers in my package. Thanks!
