### ISSUE TITLE
XEmbed Fl_Choice wrong position fix

### ISSUE THREAD

**Issue by harryhaaren** [original-male/ntk#4]
Hi,

Falktx found (and implemented) a fix for the XEmbed issue we experienced when using the Fl_Choice widget: latest commit in his NTK repo has the fix:
https://github.com/falktx/ntk

Cheers, -Harry

**Comment by trebmuh** [comment]
@original-male : I guess this issue can be closed since https://github.com/original-male/ntk/commit/5719b0044d9f267de5391fab006370cc7f4e70bd

**Comment by harryhaaren** [comment]
Thanks @trebmuh - as the reporter of the issue I can close it too, thanks for mentioning :)

**Comment by trebmuh** [comment]
All good then. Thanks @harryhaaren .
